apiVersion: v1
kind: Service
metadata:
  name: hello-nexus-service
  namespace: nexus-weaver
spec:
  selector:
    app: hello-nexus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 