apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nexus-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///home/seshu/Documents/Java/nexus-weaver
    targetRevision: HEAD
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus-weaver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 