apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: market-data-consumer-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seshuthota/nexus-weaver.git
    targetRevision: HEAD
    path: gitops/overlays/dev/market-data-consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus-weaver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 