apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seshuthota/nexus-weaver.git
    targetRevision: HEAD
    path: gitops/base/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus-weaver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 