apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-weaver

resources:
  - ../../base/hello-app

commonLabels:
  environment: dev

patchesStrategicMerge:
  - replica-patch.yaml 