apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/market-data-consumer

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

commonLabels:
  environment: dev
  
namePrefix: "" 