apiVersion: v1
kind: Service
metadata:
  name: market-data-ingestion-service
  labels:
    app: market-data-ingestion
    component: camel-service
    tier: ingestion
spec:
  selector:
    app: market-data-ingestion
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: websocket
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: market-data-ingestion-metrics
  labels:
    app: market-data-ingestion
    component: camel-service
    tier: ingestion
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: market-data-ingestion
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 